language: python

matrix:
  include:
    - python: 2.7

before_install:
  - sudo apt-get update

install:
  - pip install coveralls
  # install python dependencies
  - pip install -r requirements.txt --upgrade --target lib/
  - touch lib/google/__init__.py

script:
  # python, we run lint with coverage and display coverage output
  - bin/pylint --python=python
  - bin/coverage --python=python

after_success:
  coveralls
