language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt/launchers
matrix:
  include:
    - jdk: openjdk7
      scala: 2.11.7
script:
  - sbt compile test
  - sbt assembly
